"""
Pengaturan Django untuk proyek myproject.

Generated by 'django-admin startproject' using Django 5.0.6.

Untuk informasi lebih lanjut tentang file ini, lihat
https://docs.djangoproject.com/en/5.0/topics/settings/

Untuk daftar lengkap pengaturan dan nilainya, lihat
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os # Penting: Pastikan 'os' diimpor di awal file

# Path dasar proyek
# Ini akan menunjuk ke direktori 'TUGAS UAS' (folder root proyek)
BASE_DIR = Path(__file__).resolve().parent.parent


# --- Pengaturan Keamanan ---

# SECRET_KEY: Kunci rahasia yang digunakan untuk menyediakan kriptografi.
# SANGAT PENTING: Ganti dengan kunci yang lebih kuat dan JANGAN biarkan di sini
# secara langsung dalam produksi. Gunakan variabel lingkungan (environment variable).
SECRET_KEY = 'j0e)q7x7tru&%j-zk(u-!-tf9x@1@9_5j7d7mmazx+39&6!8vd' # GANTI INI DENGAN KUNCI YANG LEBIH AMAN SAAT DEPLOYMENT!

# DEBUG: Mengaktifkan/menonaktifkan mode debug.
# Atur ke False di produksi untuk alasan keamanan dan kinerja.
DEBUG = True

# ALLOWED_HOSTS: Daftar string yang mewakili host/nama domain yang dapat melayani proyek Django ini.
# Kosongkan untuk development (['*'] atau []). Isi dengan domain Anda untuk produksi (misal: ['www.desaboyemare.com', '127.0.0.1']).
ALLOWED_HOSTS = []


# --- Konfigurasi Aplikasi ---

# INSTALLED_APPS: Aplikasi Django yang terinstal di proyek ini.
# Pastikan semua aplikasi yang Anda gunakan terdaftar di sini.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # Ditambahkan untuk filter template seperti |intcomma
    'myapp', # Aplikasi buatan Anda
]


# --- Konfigurasi Middleware ---

# MIDDLEWARE: Komponen yang diproses dalam rantai permintaan/respons.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# --- Konfigurasi URL Root ---

# ROOT_URLCONF: Modul Python tempat Django akan mencari konfigurasi URL root Anda.
ROOT_URLCONF = 'myproject.urls' # Pastikan 'myproject' adalah nama folder proyek utama Anda


# --- Konfigurasi Template ---

# TEMPLATES: Daftar pengaturan untuk mesin template Django.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS: Direktori tempat Django akan mencari file template global.
        # Mengacu pada folder 'template' di root proyek Anda.
        'DIRS': [BASE_DIR / 'template'], # PENTING: Gunakan 'template' (tunggal) jika nama foldernya begitu.
        # APP_DIRS: Jika True, Django akan mencari folder 'templates' di setiap INSTALLED_APPS.
        'APP_DIRS': True, # Sangat penting agar template dari aplikasi lain (jika ada) juga ditemukan.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static', # Umumnya juga diperlukan untuk static files
            ],
        },
    },
]


# --- Konfigurasi WSGI ---

# WSGI_APPLICATION: Modul Python lengkap dari objek aplikasi WSGI Anda.
WSGI_APPLICATION = 'myproject.wsgi.application'


# --- Konfigurasi Database ---

# DATABASES: Pengaturan koneksi database.
# Default menggunakan SQLite untuk pengembangan.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', # Lokasi file database SQLite di root proyek
    }
}


# --- Validasi Password ---

# AUTH_PASSWORD_VALIDATORS: Validator yang digunakan untuk memeriksa kekuatan password pengguna.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Bahasa & Zona Waktu ---

# LANGUAGE_CODE: Kode bahasa default untuk situs Anda.
LANGUAGE_CODE = 'en-us' # Anda bisa mengubah ini menjadi 'id' atau 'id-id' untuk Bahasa Indonesia

# TIME_ZONE: Zona waktu default untuk situs Anda.
TIME_ZONE = 'Asia/Makassar' # Disarankan WITA (GMT+8). Jika ingin WIB, gunakan 'Asia/Jakarta' (GMT+7).

# USE_I18N: Mengaktifkan sistem terjemahan Django.
USE_I18N = True

# USE_TZ: Mengaktifkan dukungan zona waktu yang sadar (timezone-aware datetimes).
USE_TZ = True


# --- Konfigurasi File Statis (CSS, JavaScript, Gambar Tema) ---

# STATIC_URL: URL yang akan digunakan saat merujuk file statis yang berlokasi di STATIC_ROOT.
STATIC_URL = 'static/'

# STATICFILES_DIRS: Daftar direktori tambahan tempat aplikasi staticfiles akan mencari file statis.
# Mengacu pada folder 'static' di root proyek Anda.
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Menunjuk ke folder 'static' di root proyek
]

# STATIC_ROOT: Direktori absolut tempat file statis yang dikumpulkan untuk deployment.
# Ini adalah tempat 'python manage.py collectstatic' akan menempatkan semua file statis.
# Biasa digunakan saat deployment, tidak selalu dibutuhkan di development.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_collected')


# --- Konfigurasi File Media (Gambar yang Diunggah Pengguna, misalnya logo UMKM) ---

# MEDIA_URL: URL publik dasar yang melayani file media yang diunggah pengguna.
# Ini akan menjadi URL seperti 'http://127.0.0.1:8000/media/...'
MEDIA_URL = 'media/'

# MEDIA_ROOT: Jalur absolut ke direktori tempat file media yang diunggah akan disimpan.
# File akan disimpan di 'TUGAS UAS/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --- Konfigurasi Default Primary Key ---

# DEFAULT_AUTO_FIELD: Tipe field primary key default untuk model yang tidak menentukan pk secara eksplisit.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# your_project/settings.py
USE_TZ = True # Ini penting untuk filtering tanggal/waktu yang akurat
TIME_ZONE = 'Asia/Makassar' # Atau 'Asia/Jakarta', 'Asia/Jayapura' sesuai lokasi WITA