# Generated by Django 5.2.3 on 2025-06-26 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APBDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(unique=True)),
                ('total_pendapatan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_belanja', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sisa_lebih_pembiayaan_anggaran', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('link_dokumen_resmi', models.URLField(blank=True, max_length=500, null=True)),
                ('tanggal_publikasi', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Data APBDesa',
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('gambar_utama', models.ImageField(blank=True, help_text='Unggah gambar utama untuk artikel ini.', null=True, upload_to='article_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Artikel & Berita',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelapor', models.CharField(max_length=100)),
                ('email_pelapor', models.EmailField(blank=True, max_length=254, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('jenis_pengaduan', models.CharField(choices=[('', '[ PILIH JENIS PENGADUAN ]'), ('Administrasi Kependudukan', 'Administrasi Kependudukan'), ('Jalan & Infrastruktur', 'Jalan & Infrastruktur'), ('Bantuan Sosial / BLT', 'Bantuan Sosial / BLT'), ('Lingkungan Hidup', 'Lingkungan Hidup'), ('Sengketa Tanah / Warga', 'Sengketa Tanah / Warga'), ('Pelayanan Pemerintah Desa', 'Pelayanan Pemerintah Desa'), ('Keamanan & Ketertiban', 'Keamanan & Ketertiban')], default='', help_text='Pilih jenis pengaduan Anda.', max_length=100)),
                ('judul_pengaduan', models.CharField(max_length=200)),
                ('isi_pengaduan', models.TextField()),
                ('tanggal_pengaduan', models.DateTimeField(auto_now_add=True)),
                ('bukti_foto', models.ImageField(blank=True, help_text='Unggah foto sebagai bukti jika ada.', null=True, upload_to='pengaduan_bukti/')),
                ('status_pengaduan', models.CharField(choices=[('Baru', 'Baru'), ('Dalam Proses', 'Dalam Proses'), ('Selesai', 'Selesai'), ('Ditolak', 'Ditolak')], default='Baru', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Pengaduan',
            },
        ),
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_umkm', models.CharField(max_length=150)),
                ('jenis_usaha', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('nama_pemilik', models.CharField(max_length=100)),
                ('kontak_pemilik', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tahun_berdiri', models.IntegerField(blank=True, null=True)),
                ('logo_umkm', models.ImageField(blank=True, null=True, upload_to='umkm_logos/')),
            ],
            options={
                'verbose_name_plural': 'Daftar UMKM',
            },
        ),
        migrations.CreateModel(
            name='DetailAPBDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deskripsi_item', models.TextField(blank=True, null=True)),
                ('apbdesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.apbdesa')),
            ],
            options={
                'verbose_name_plural': 'Detail APBDesa',
            },
        ),
    ]
