# Generated by Django 5.2.3 on 2025-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotensiDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_potensi', models.CharField(choices=[('Wisata', 'Wisata'), ('Pertanian', 'Pertanian'), ('Budaya', 'Budaya'), ('UMKM', 'UMKM'), ('Lain-lain', 'Lain-lain')], help_text='Pilih jenis potensi desa ini (misal: Wisata, Pertanian).', max_length=50)),
                ('nama_potensi', models.CharField(max_length=200, verbose_name='Nama Potensi / Judul')),
                ('deskripsi', models.TextField(help_text='Deskripsi lengkap tentang potensi ini.')),
                ('gambar_utama', models.ImageField(blank=True, help_text='Unggah gambar yang merepresentasikan potensi ini.', null=True, upload_to='potensi_desa_images/')),
                ('lokasi', models.CharField(blank=True, help_text='Lokasi spesifik potensi ini (contoh: Dukuh A, Jalur Sungai).', max_length=255, null=True)),
                ('link_detail', models.URLField(blank=True, help_text='Link eksternal (misal: Google Maps, artikel terkait) atau biarkan kosong jika tidak ada.', max_length=500, null=True)),
                ('tanggal_publikasi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Potensi Desa',
                'ordering': ['jenis_potensi', 'nama_potensi'],
            },
        ),
        migrations.AlterModelOptions(
            name='umkm',
            options={'ordering': ['nama_umkm'], 'verbose_name_plural': 'Daftar UMKM'},
        ),
        migrations.AddField(
            model_name='umkm',
            name='gambar_produk',
            field=models.ImageField(blank=True, help_text='Unggah gambar produk utama atau tampilan UMKM ini.', null=True, upload_to='umkm_produk_images/'),
        ),
        migrations.AddField(
            model_name='umkm',
            name='link_medsos',
            field=models.URLField(blank=True, null=True, verbose_name='Link Media Sosial/Website'),
        ),
        migrations.AddField(
            model_name='umkm',
            name='no_telepon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon/WA'),
        ),
    ]
