# Generated by Django 5.2.3 on 2025-07-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_potensidesa_alter_umkm_options_umkm_gambar_produk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKependudukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_penduduk', models.IntegerField(default=0)),
                ('jumlah_laki_laki', models.IntegerField(default=0)),
                ('jumlah_perempuan', models.IntegerField(default=0)),
                ('jumlah_kk', models.IntegerField(default=0)),
                ('mayoritas_pekerjaan', models.CharField(default='petani, buruh, dan pelaku UMKM', max_length=255)),
                ('tingkat_pendidikan_umum', models.CharField(default='bervariasi dari SD hingga perguruan tinggi', max_length=255)),
                ('keberagaman_budaya', models.CharField(default='agama dan suku yang hidup rukun', max_length=255)),
                ('luas_wilayah', models.CharField(blank=True, help_text='Contoh: 12.34 km persegi', max_length=100, null=True)),
                ('batas_wilayah', models.TextField(blank=True, help_text='Contoh: Utara: Desa A, Selatan: Desa B, dst.', null=True)),
                ('jumlah_dusun', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Data Kependudukan & Wilayah',
            },
        ),
        migrations.CreateModel(
            name='IdentitasUmum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_desa', models.CharField(default='Boyemare', max_length=100)),
                ('nama_kecamatan', models.CharField(default='Sakra Barat', max_length=100)),
                ('nama_kabupaten', models.CharField(default='Lombok Timur', max_length=100)),
                ('nama_provinsi', models.CharField(default='Nusa Tenggara Barat', max_length=100)),
                ('nama_kepala_desa', models.CharField(default='Ahmad Fathullah', max_length=100)),
                ('sejarah_desa', models.TextField(help_text='Sejarah panjang desa, termasuk sebagai komunitas agraris, dll.')),
                ('alamat_kantor', models.CharField(default='Jalan Raya Boyemare No. 123, Kec. Sakra Barat', max_length=255)),
                ('email_resmi', models.EmailField(blank=True, default='desaboyemare@example.com', max_length=255, null=True)),
                ('telepon_resmi', models.CharField(blank=True, default='+62 812-3456-7890', max_length=50, null=True)),
                ('visi_desa', models.TextField(blank=True, help_text='Visi Desa Boyemare', null=True)),
                ('misi_desa', models.TextField(blank=True, help_text='Misi Desa Boyemare (gunakan baris baru untuk setiap poin)', null=True)),
            ],
            options={
                'verbose_name_plural': '1. Identitas Umum Desa',
            },
        ),
        migrations.CreateModel(
            name='JabatanPejabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=100, unique=True)),
                ('urutan', models.IntegerField(default=99, help_text='Untuk mengatur urutan tampilan jabatan')),
            ],
            options={
                'verbose_name': 'Jabatan Pejabat',
                'verbose_name_plural': 'Jabatan Pejabat',
                'ordering': ['urutan', 'nama_jabatan'],
            },
        ),
        migrations.CreateModel(
            name='PemerintahanDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_umum', models.TextField(help_text='Deskripsi umum tentang pemerintahan desa (Kepala Desa, perangkat, BPD)')),
                ('lembaga_pendukung', models.TextField(help_text='Dukungan lembaga seperti PKK, Karang Taruna, LPMD (pisahkan dengan koma atau enter)')),
                ('proses_perencanaan', models.TextField(help_text='Proses perencanaan pembangunan (RPJMDes, RKPDes)')),
            ],
            options={
                'verbose_name_plural': '3. Pemerintahan Desa (Umum)',
            },
        ),
        migrations.CreateModel(
            name='SaranaPrasarana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akses_jalan_utama', models.TextField(help_text='Deskripsi akses jalan utama')),
                ('fasilitas_pendidikan', models.TextField(help_text='Contoh: PAUD, TK, SD, SMP, SMA')),
                ('layanan_kesehatan', models.TextField(help_text='Contoh: Puskesmas Pembantu, Posyandu, Bidan Desa')),
                ('tempat_ibadah', models.TextField(help_text='Contoh: Masjid, Gereja, Pura (pisahkan dengan koma)')),
                ('jaringan_listrik_air', models.TextField(help_text='Deskripsi cakupan jaringan listrik dan air bersih')),
                ('fasilitas_umum_lain', models.TextField(blank=True, help_text='Contoh: pasar, balai desa, jaringan internet, dll.', null=True)),
                ('peta_embed_code', models.TextField(blank=True, help_text="Kode embed Google Maps untuk peta desa (misal: dari 'Sematkan peta' di Google Maps)", null=True)),
            ],
            options={
                'verbose_name_plural': '4. Sarana dan Prasarana Umum',
            },
        ),
        migrations.CreateModel(
            name='PejabatDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pejabat_desa/')),
                ('periode_jabatan', models.CharField(blank=True, help_text='Contoh: 2020-2025', max_length=100, null=True)),
                ('kontak_info', models.CharField(blank=True, help_text='Kontak atau informasi lain (opsional)', max_length=255, null=True)),
                ('urutan_tampil', models.IntegerField(default=99, help_text='Untuk mengatur urutan tampilan pejabat')),
                ('jabatan', models.ForeignKey(blank=True, help_text='Pilih jabatan dari daftar yang tersedia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.jabatanpejabat')),
            ],
            options={
                'verbose_name': 'Pejabat Desa',
                'verbose_name_plural': '3a. Daftar Pejabat Desa',
                'ordering': ['urutan_tampil', 'nama_lengkap'],
            },
        ),
    ]
