# Generated by Django 5.2.3 on 2025-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_datakependudukan_identitasumum_jabatanpejabat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WisataCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wisata_carousel/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan gambar (lebih kecil muncul lebih dulu)')),
            ],
            options={
                'verbose_name': 'Gambar Carousel Wisata',
                'verbose_name_plural': 'Gambar Carousel Wisata',
                'ordering': ['order'],
            },
        ),
    ]
