# Generated by Django 5.2.3 on 2025-07-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_wisatacarouselimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saranaprasarana',
            name='peta_embed_code',
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='akomodasi_kuliner_sekitar',
            field=models.TextField(blank=True, help_text='Informasi penginapan dan tempat makan di sekitar lokasi. Pisahkan dengan baris baru.', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='embed_video_link',
            field=models.URLField(blank=True, help_text='Link video YouTube/Vimeo (opsional).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='harga_tiket',
            field=models.CharField(blank=True, help_text='Contoh: Gratis, Rp 10.000/orang, Bervariasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='jam_operasional',
            field=models.CharField(blank=True, help_text='Contoh: Setiap hari, 08.00 - 17.00 WITA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='kegiatan_atraksi',
            field=models.TextField(blank=True, help_text='Daftar kegiatan atau atraksi unggulan yang bisa dilakukan. Pisahkan dengan baris baru.', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='pengelola_kontak',
            field=models.TextField(blank=True, help_text='Nama pengelola dan informasi kontak (telepon/email).', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='peta_embed_code',
            field=models.TextField(blank=True, help_text="Kode embed Google Maps untuk lokasi potensi ini (misal: dari 'Sematkan peta' di Google Maps).", null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='tips_peringatan',
            field=models.TextField(blank=True, help_text='Tips untuk pengunjung dan peringatan penting. Pisahkan dengan baris baru.', null=True),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='deskripsi',
            field=models.TextField(help_text='Deskripsi singkat atau daya tarik utama potensi ini.'),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='gambar_utama',
            field=models.ImageField(blank=True, help_text='Unggah gambar utama yang merepresentasikan potensi ini.', null=True, upload_to='potensi_desa_images/'),
        ),
        migrations.CreateModel(
            name='PotensiGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='potensi_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan gambar dalam galeri')),
                ('potensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='myapp.potensidesa')),
            ],
            options={
                'verbose_name': 'Gambar Galeri Potensi',
                'verbose_name_plural': 'Gambar Galeri Potensi',
                'ordering': ['order'],
            },
        ),
    ]
