# Generated by Django 5.2.3 on 2025-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_saranaprasarana_peta_embed_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potensidesa',
            name='fasilitas',
            field=models.TextField(blank=True, help_text='Daftar fasilitas yang tersedia di lokasi wisata. Pisahkan dengan baris baru.', null=True),
        ),
    ]
