# Generated by Django 5.2.3 on 2025-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_potensidesa_fasilitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='potensidesa',
            name='alamat_umkm_detail',
            field=models.TextField(blank=True, help_text='Alamat lokasi usaha UMKM. (Khusus UMKM)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='bahan_baku_umkm',
            field=models.CharField(blank=True, help_text='Bahan baku: Lokal atau dari luar? (Khusus UMKM)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='deskripsi_makna_budaya',
            field=models.TextField(blank=True, help_text='Deskripsi & makna budaya. (Khusus Budaya)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='deskripsi_produk_umkm',
            field=models.TextField(blank=True, help_text='Deskripsi singkat produk / jasa UMKM. (Khusus UMKM)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='jenis_budaya_kesenian',
            field=models.CharField(blank=True, help_text='Jenis: Seni pertunjukan, tradisi adat, tarian, musik, pakaian, kuliner khas, dll. (Khusus Budaya)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='jenis_sda',
            field=models.CharField(blank=True, help_text='Jenis SDA: Hayati / Non-hayati (air, tanah, mineral, hasil hutan, hasil laut, dll). (Khusus SDA)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='jenis_usaha_umkm',
            field=models.CharField(blank=True, help_text='Jenis Usaha: Makanan, kerajinan, pakaian, pertanian olahan, dll. (Khusus UMKM)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='kendala_pengembangan_sda',
            field=models.TextField(blank=True, help_text='Kendala dan potensi pengembangan SDA. Pisahkan dengan baris baru. (Khusus SDA)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='kontak_narahubung_budaya',
            field=models.CharField(blank=True, help_text='Kontak Narahubung (bila ingin tampil di event). (Khusus Budaya)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='kontak_umkm_detail',
            field=models.TextField(blank=True, help_text='Nomor HP, WA, Sosmed UMKM. Pisahkan dengan baris baru. (Khusus UMKM)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='legalitas_umkm',
            field=models.CharField(blank=True, help_text='Legalitas Usaha: (NIB, PIRT, Halal, BPOM, dll). Pisahkan dengan koma. (Khusus UMKM)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='link_pendukung_sda',
            field=models.URLField(blank=True, help_text='Link pendukung terkait SDA (jika ada). (Khusus SDA)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='luas_lokasi_sda',
            field=models.TextField(blank=True, help_text='Luas lahan, letak geografis, akses menuju lokasi SDA. (Khusus SDA)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='nama_budaya_kesenian',
            field=models.CharField(blank=True, help_text='Nama Budaya/Kesenian (misal: Gendang Beleq, Peresean, Tari Gandrung). (Khusus Budaya)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='nama_produk_umkm',
            field=models.CharField(blank=True, help_text='Nama UMKM / Produk Unggulan. (Khusus UMKM)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='nilai_ekonomi_sda',
            field=models.TextField(blank=True, help_text='Dampak terhadap ekonomi desa dari SDA. (Khusus SDA)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='nilai_historis_filosofis',
            field=models.TextField(blank=True, help_text='Nilai Historis atau Filosofis budaya. (Khusus Budaya)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='pelaku_penampil',
            field=models.TextField(blank=True, help_text='Pelaku/Penampil: Kelompok seni, tokoh adat. Pisahkan dengan baris baru. (Khusus Budaya)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='pemanfaatan_sda',
            field=models.TextField(blank=True, help_text='Bagaimana potensi SDA digunakan saat ini? Oleh siapa? (Khusus SDA)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='pemasaran_umkm',
            field=models.CharField(blank=True, help_text='Pemasaran: Offline (pasar lokal) / Online (Shopee, WA, Instagram). (Khusus UMKM)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='pengelola_sda',
            field=models.CharField(blank=True, help_text='Dikelola oleh BUMDes, Kelompok Tani Hutan, dll. (Khusus SDA)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='potensi_wisata_budaya',
            field=models.TextField(blank=True, help_text='Potensi Wisata Budaya. (Khusus Budaya)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='skala_produksi_umkm',
            field=models.CharField(blank=True, help_text='Skala produksi & jumlah pekerja. (Khusus UMKM)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='upaya_pelestarian',
            field=models.TextField(blank=True, help_text='Upaya Pelestarian: Dukungan desa, sekolah, komunitas. Pisahkan dengan baris baru. (Khusus Budaya)', null=True),
        ),
        migrations.AddField(
            model_name='potensidesa',
            name='waktu_tempat_pelaksanaan',
            field=models.TextField(blank=True, help_text='Waktu & Tempat Pelaksanaan (jika event/tahunan). Pisahkan dengan baris baru. (Khusus Budaya)', null=True),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='akomodasi_kuliner_sekitar',
            field=models.TextField(blank=True, help_text='Informasi penginapan dan tempat makan di sekitar lokasi. Pisahkan dengan baris baru. (Khusus Wisata)', null=True),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='fasilitas',
            field=models.TextField(blank=True, help_text='Daftar fasilitas yang tersedia di lokasi wisata. Pisahkan dengan baris baru. (Khusus Wisata)', null=True),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='harga_tiket',
            field=models.CharField(blank=True, help_text='Contoh: Gratis, Rp 10.000/orang, Bervariasi (Khusus Wisata)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='jam_operasional',
            field=models.CharField(blank=True, help_text='Contoh: Setiap hari, 08.00 - 17.00 WITA (Khusus Wisata)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='jenis_potensi',
            field=models.CharField(choices=[('Wisata', 'Wisata'), ('SDA', 'Sumber Daya Alam'), ('UMKM', 'Usaha Mikro, Kecil, dan Menengah'), ('Budaya', 'Budaya & Kesenian Tradisional'), ('Lain-lain', 'Lain-lain')], help_text='Pilih jenis potensi desa ini (misal: Wisata, Sumber Daya Alam).', max_length=50),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='kegiatan_atraksi',
            field=models.TextField(blank=True, help_text='Daftar kegiatan atau atraksi unggulan yang bisa dilakukan. Pisahkan dengan baris baru. (Khusus Wisata)', null=True),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='pengelola_kontak',
            field=models.TextField(blank=True, help_text='Nama pengelola dan informasi kontak (telepon/email). (Khusus Wisata)', null=True),
        ),
        migrations.AlterField(
            model_name='potensidesa',
            name='tips_peringatan',
            field=models.TextField(blank=True, help_text='Tips untuk pengunjung dan peringatan penting. Pisahkan dengan baris baru. (Khusus Wisata)', null=True),
        ),
    ]
