# Generated by Django 5.2.3 on 2025-07-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_potensidesa_alamat_umkm_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_potensi', models.CharField(choices=[('Wisata', 'Wisata'), ('SDA', 'Sumber Daya Alam'), ('UMKM', 'Usaha Mikro, Kecil, dan Menengah'), ('Budaya', 'Budaya & Kesenian Tradisional'), ('Umum', 'Umum (untuk halaman lain jika diperlukan)')], default='Umum', help_text='Pilih jenis potensi yang akan menggunakan gambar ini di carousel hero.', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan gambar (lebih kecil muncul lebih dulu)')),
            ],
            options={
                'verbose_name': 'Gambar Carousel Hero',
                'verbose_name_plural': 'Gambar Carousel Hero',
                'ordering': ['jenis_potensi', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='WisataCarouselImage',
        ),
    ]
